### ISSUE TITLE
Unable to skip title screen (O3DS, HW/SW versions)

### ISSUE THREAD

**Issue by SombrAbsol** [SaturnSH2x2/Sonic-CD-11-3DS#12]
Hi

I heard that Sonic CD now supports the O3DS. I wanted to test it on mine, but despite all the button combinations and touching the touch screen, impossible to get past the title screen. Did I do something wrong?

The Data.rsdk file is from the Android version. It does it to me with the HW and SW versions.

**Comment by lividhen** [comment]
I think this is a duplicate of #10

**Comment by SaturnSH2x2** [comment]
Yeah, this appears to be a duplicate. I'll mark it as such and close, all discussion should be on #10 instead.
