### ISSUE TITLE
Directory write error prevents mod loading

### ISSUE THREAD

**Issue by Gareth-McCullough** [SaturnSH2x2/Sonic-CD-11-3DS#7]
Mods do not actually load, because the game tries to write to sd:/3ds/SonicCD/mods//modconfig.ini instead of sd:/3ds/SonicCD/mods/modconfig.ini.

I am running this on a New Nintendo 2DS XL, using the latest SW CIA version, if that helps.

![2021-08-14_23-17-36](https://user-images.githubusercontent.com/48102916/129466048-4ae92155-39bc-43cb-aad7-c16244c1fe63.png)

**Comment by SaturnSH2x2** [comment]
While testing, mods loaded, however, config settings would be reset upon re-entering the mod menu.

Regardless, this should be fixed as of fb757b1d769e074e0986b3612cb1ee30ba809a44.
